
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEDIVIDE ELSE ELSEIF EQUAL FOR ID IF INT LPAREN MINUS NUMBER PLUS RPAREN TIMES WHILEprogram : program statementprogram : statementstatement : ID EQUAL expressionexpression : expression PLUS expression \n| expression MINUS expressionexpression : expression DIVIDE expression\n| expression TIMES expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : IDtype : INTstatement : type ID EQUAL expressionstatement : type ID'
    
_lr_action_items = {'ID':([0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,],[3,3,-2,8,-11,-1,9,-13,-10,-3,9,-9,9,9,9,9,9,-12,-4,-5,-6,-7,-8,]),'INT':([0,1,2,6,8,9,10,12,19,20,21,22,23,24,],[5,5,-2,-1,-13,-10,-3,-9,-12,-4,-5,-6,-7,-8,]),'$end':([1,2,6,8,9,10,12,19,20,21,22,23,24,],[0,-2,-1,-13,-10,-3,-9,-12,-4,-5,-6,-7,-8,]),'EQUAL':([3,8,],[7,13,]),'LPAREN':([7,11,13,14,15,16,17,],[11,11,11,11,11,11,11,]),'NUMBER':([7,11,13,14,15,16,17,],[12,12,12,12,12,12,12,]),'PLUS':([9,10,12,18,19,20,21,22,23,24,],[-10,14,-9,14,14,-4,-5,-6,-7,-8,]),'MINUS':([9,10,12,18,19,20,21,22,23,24,],[-10,15,-9,15,15,-4,-5,-6,-7,-8,]),'DIVIDE':([9,10,12,18,19,20,21,22,23,24,],[-10,16,-9,16,16,16,16,-6,-7,-8,]),'TIMES':([9,10,12,18,19,20,21,22,23,24,],[-10,17,-9,17,17,17,17,-6,-7,-8,]),'RPAREN':([9,12,18,20,21,22,23,24,],[-10,-9,24,-4,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,1,],[2,6,]),'type':([0,1,],[4,4,]),'expression':([7,11,13,14,15,16,17,],[10,18,19,20,21,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program statement','program',2,'p_program_multiple','parser.py',20),
  ('program -> statement','program',1,'p_program_single','parser.py',24),
  ('statement -> ID EQUAL expression','statement',3,'p_statement_assign','parser.py',29),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',34),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',35),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_muldiv','parser.py',39),
  ('expression -> expression TIMES expression','expression',3,'p_expression_muldiv','parser.py',40),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',45),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',50),
  ('expression -> ID','expression',1,'p_expression_id','parser.py',55),
  ('type -> INT','type',1,'p_type','parser.py',60),
  ('statement -> type ID EQUAL expression','statement',4,'p_declaration','parser.py',65),
  ('statement -> type ID','statement',2,'p_declaration_no_assign','parser.py',70),
]
